package rri.fixbot.ruleset.huawei.constants

enum class Warnings {
    CLASS_NAME_INCORRECT,
    CONSTANT_UPPERCASE,
    ENUM_VALUE,
    EXCEPTION_SUFFIX,
    FILE_NAME_INCORRECT,
    FILE_NAME_MATCH_CLASS,
    FUNCTION_BOOLEAN_PREFIX,
    FUNCTION_NAME_INCORRECT_CASE,
    GENERIC_NAME,
    IDENTIFIER_LENGTH,
    OBJECT_NAME_INCORRECT,
    PACKAGE_NAME_INCORRECT,
    PACKAGE_NAME_INCORRECT_CASE,
    PACKAGE_NAME_INCORRECT_PREFIX,
    PACKAGE_NAME_INCORRECT_SYMBOLS,
    PACKAGE_NAME_MISSING,
    VARIABLE_HAS_PREFIX,
    VARIABLE_NAME_INCORRECT,
    VARIABLE_NAME_INCORRECT_FORMAT,
}
