package test.paragraph3.long_line

// hello world! dfhgkdhfgkdhfkjghdjkfhgkjdhfgkjhdfkgdkfghdkjfhgkdhfgkjdhgjkhdjkfghdkjfghdjkfhgjkdhfgjkdhfjghdkjfghdkjghkdjhfgkjdfhgkjdhgfkdhfgdgfdjgfhfdkjg
// kdjfhgkdfhkjgdhkfghdfhgkdgdkjdhfgkjhkjfghkdhgfjdfhhh
fun foo() {

}